/* Generated by tools/bm_pricing.py. Edit REPLACEMENTS in tools/bm_pricing_rules.py, then regenerate. */
(function () {
  'use strict';
  var rules = __RULES__;
  function positions(source, old) {
    var result = [], index = source.indexOf(old), startsNumber = /^[0-9]/.test(old);
    while (index !== -1) {
      if (!startsNumber || index === 0 || !/[0-9,.]/.test(source[index - 1])) result.push(index);
      index = source.indexOf(old, index + old.length);
    }
    return result;
  }
  function text(value) {
    if (typeof value !== 'string') return value;
    rules.forEach(function (rule) {
      positions(value, rule[0]).reverse().forEach(function (start) {
        value = value.slice(0, start) + rule[1] + value.slice(start + rule[0].length);
      });
    });
    return value;
  }
  function html(value) {
    if (!value) return value;
    var template = document.createElement('template');
    template.innerHTML = value;
    var walker = document.createTreeWalker(template.content, NodeFilter.SHOW_TEXT);
    var nodes = [], node;
    while ((node = walker.nextNode())) {
      if (!node.parentElement || !node.parentElement.closest('script, style')) nodes.push(node);
    }
    rules.forEach(function (rule) {
      var source = nodes.map(function (n) { return n.nodeValue; }).join('');
      var prefix = 0, suffix = 0;
      while (prefix < Math.min(rule[0].length, rule[1].length) && rule[0][prefix] === rule[1][prefix]) prefix++;
      while (suffix < Math.min(rule[0].length, rule[1].length) - prefix &&
        rule[0][rule[0].length - suffix - 1] === rule[1][rule[1].length - suffix - 1]) suffix++;
      var replacement = rule[1].slice(prefix, suffix ? -suffix : undefined);
      positions(source, rule[0]).reverse().forEach(function (start) {
        var end = start + rule[0].length - suffix, offset = 0;
        start += prefix;
        nodes.forEach(function (n) {
          var part = n.nodeValue, right = offset + part.length;
          if (offset < end && right > start) {
            var a = Math.max(0, start - offset), b = Math.min(part.length, end - offset);
            n.nodeValue = part.slice(0, a) + (offset <= start ? replacement : '') + part.slice(b);
          }
          offset = right;
        });
      });
    });
    return template.innerHTML;
  }
  function post(value) {
    if (Array.isArray(value)) return value.map(post);
    if (!value || typeof value !== 'object') return value;
    var result = Object.assign({}, value);
    ['title_ja', 'excerpt_ja'].forEach(function (key) {
      if (typeof result[key] === 'string') result[key] = text(result[key]);
    });
    if (typeof result.content === 'string') result.content = html(result.content);
    return result;
  }
  window.bmPricing = { text: text, html: html, post: post };
})();
