"""Shared sitemap markup; callers own URL selection and lastmod policy."""

import re


def remove_blocks(source, name):
    pattern = re.compile(
        rf"\s*<!-- BUILD:{re.escape(name)}[^>]*?-->[\s\S]*?<!-- /BUILD:{re.escape(name)} -->\s*"
    )
    return pattern.sub("\n\n", source)


def url_entry(url, modified, *, frequency, priority):
    lastmod = f"    <lastmod>{modified}</lastmod>\n" if modified else ""
    return (
        "  <url>\n"
        f"    <loc>{url}</loc>\n"
        f"{lastmod}"
        f"    <changefreq>{frequency}</changefreq>\n"
        f"    <priority>{priority}</priority>\n"
        "  </url>"
    )


def build_block(name, entries, *, generator):
    return (
        f"  <!-- BUILD:{name} (auto-generated by {generator}) -->\n"
        + "\n".join(entries)
        + f"\n  <!-- /BUILD:{name} -->\n"
    )


def append_blocks(source, *blocks):
    return source.replace("</urlset>", "\n".join(b for b in blocks if b) + "\n</urlset>")
